name: re_video_library
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.0.0
  video_player: ^2.8.1
  screen_brightness: ^1.0.0
  share_plus: ^10.1.0
flutter:
  uses-material-design: true
